In [1]:
import pandas as pd
import numpy as np
import altair as alt
import sklearn
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from numpy import array, hstack
import pickle


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\sbmoi\Anaconda\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\sbmoi\Anaconda\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\sbmoi\Anaconda\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\sbmoi\Anaconda\lib\site-packages\traitlets\config\application.py", line 846, in launch_instance
    app.start()
  File "C:\Users\sbmoi\Anaconda\lib\site-packages\

AttributeError: _ARRAY_API not found


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\sbmoi\Anaconda\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\sbmoi\Anaconda\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\sbmoi\Anaconda\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\sbmoi\Anaconda\lib\site-packages\traitlets\config\application.py", line 846, in launch_instance
    app.start()
  File "C:\Users\sbmoi\Anaconda\lib\site-packages\

AttributeError: _ARRAY_API not found

# Original

In [4]:
#link = 'processed_data_pickle_files_no_smoothing/'
link = '../data/batched_data_pickle_files/'

with open(link + 'processed_test_data.pkl', 'rb') as file:
    test = pickle.load(file)
    
with open(link + 'processed_train_data.pkl', 'rb') as file:
    train = pickle.load(file)    
    
with open(link + 'processed_train_targets.pkl', 'rb') as file:
    y_train = pickle.load(file)
    
with open(link + 'true_rul.pkl', 'rb') as file:
    y_test = pickle.load(file)

# New

In [5]:
#link = 'processed_data_pickle_files_no_smoothing/'
link = '../data/processed_data_pickle_files_no_smoothing/'

with open(link + 'test_data_batches.pkl', 'rb') as file:
    new_test = pickle.load(file)
    
with open(link + 'train_data_batches.pkl', 'rb') as file:
    new_train = pickle.load(file)    
    
with open(link + 'train_target_values.pkl', 'rb') as file:
    new_y_train = pickle.load(file)
    
with open(link + 'true_rul_values.pkl', 'rb') as file:
    new_y_test = pickle.load(file)

In [6]:
new_test is test

False

In [9]:
new_train is train

False

In [12]:
print(new_train[0, 0:3, 0:3])
print(train[0, 0:3, 0:3])

[[-0.24184719  0.23762537 -1.05037506]
 [ 0.51809027  0.37300294  0.20401549]
 [ 1.19803431 -1.24663472 -0.03375207]]
[[-0.70180933 -0.12446885 -0.32485068]
 [-2.10169412 -1.03133545 -1.32925197]
 [-0.86179617 -0.46862146 -0.72261137]]


In [15]:
print(train.shape)
print(y_train.shape)
print(test.shape)
print(y_test.shape)

(17731, 30, 14)
(17731,)
(100, 30, 14)
(100,)


In [16]:
print(new_train.shape)
print(new_y_train.shape)
print(new_test.shape)
print(new_y_test.shape)

(17731, 30, 14)
(17731,)
(100, 30, 14)
(100,)


In [17]:
print(new_test[0, 0:3, 0:3])
print(test[0, 0:3, 0:3])

[[-1.90850157  0.0701159  -1.39283595]
 [-0.03763635 -0.23169801 -0.50767562]
 [-0.08752609 -0.79535047  0.25188763]]
[[-1.94170729 -0.33813706 -1.50146679]
 [-0.44183073 -0.58442637 -0.84371727]
 [-0.48182744 -1.04438389 -0.27929708]]
